### ISSUE TITLE
Implement Actions and Generators

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#21]
### Components

| Name              | Properties | DataType | SocketType | Description                                                |
|-------------------|------------|----------|------------|------------------------------------------------------------|
| action            | trigger    | bool     | input      | Triggers an action on `true`                               |
|                   | result     | any      | output     | The datatype may be overridden by the concrete entity type |
|                   |
| generator         | trigger    | bool     | input      | Produces triggers (signals boolean `true`)                 |
|                   |

### Tasks

- [x] Plugin Logical
  - [x] Provide components
  - [x] Apply new components on existing entity types which are either an action or a generator
  - [x] Implement Behaviour Toggle (incoming trigger toggles outgoing boolean)
- [x] Plugin Arithmetic
  - [x] Implement Behaviour Counter (incoming trigger increases outgoing number)
- [x] Plugin Random
  - [x] Implement Behaviour PseudoRandomNumber (with seed in order to get reproducible results)
  - [x] Implement Behaviour RandomBool
  - [x] Implement Behaviour RandomString
