### ISSUE TITLE
Event System for Type System and Instance System

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#23]
### Goal

Notify about created or deleted `component`s, `entity type`s, `relation type`s, `entity instance`s, `relation instance`s and `flow`s.

### Use cases

- Get notified if an entity instance has been created or deleted in plugins and via GraphQL subscription in the user interface

### Tasks

- [x] Create Component `event`
  - [x] Property `event`
  - This is a required component in the application core
- [x] Create entity type `system_event`
  - This is a required entity type in the application core
- [x] Component Events
  - [x] Create entity instance `/org/inexor/events/types/components/created`
  - [x] Create entity instance `/org/inexor/events/types/components/deleted`
  - [x] Emit event on component creation
  - [x] Emit event on component deletion
- [x] Entity Type Events
  - [x] Create entity instance `/org/inexor/events/types/entities/created`
  - [x] Create entity instance `/org/inexor/events/types/entities/deleted`
  - [x] Emit event on entity type creation
  - [x] Emit event on entity type deletion
- [x] Relation Type Events
  - [x] Create entity instance `/org/inexor/events/types/relations/created`
  - [x] Create entity instance `/org/inexor/events/types/relations/deleted`
  - [x] Emit event on relation type creation
  - [x] Emit event on relation type deletion
- [x] Entity Instance Events
  - [x] Create entity instance `/org/inexor/events/instances/entities/created`
  - [x] Create entity instance `/org/inexor/events/instances/entities/deleted`
  - [x] Emit event on entity instance creation
  - [x] Emit event on entity instance deletion
- [x] Relation Instance Events
  - [x] Create entity instance `/org/inexor/events/instances/relations/created`
  - [x] Create entity instance `/org/inexor/events/instances/relations/deleted`
  - [x] Emit event on relation instance creation
  - [x] Emit event on relation instance deletion
- [x] Flow Events
  - [x] Create entity instance "/org/inexor/events/flows/created"
  - [x] Create entity instance "/org/inexor/events/flows/deleted"
  - [x] Emit event on flow creation
  - [x] Emit event on flow deletion
- [x] GraphQL: Provide example subscriptions

#### Components

| Name  | Properties    | Data Type | Socket Type |
|-------|---------------|-----------|-------------|
| Event | event         | any       | output      |

#### Entity Types

| Name                  | Component | Description                                                                                                             |
|-----------------------|-----------|-------------------------------------------------------------------------------------------------------------------------|
| ComponentEvent        | event     | Name of the component                                                                                                   |
|                       | label     | <ul><li>/org/inexor/events/types/components/created</li><li>/org/inexor/events/types/components/deleted</li></ul>       |
||
| EntityTypeEvent       | event     | Name of the entity type                                                                                                 |
|                       | label     | <ul><li>/org/inexor/events/types/entities/created</li><li>/org/inexor/events/types/entities/deleted</li></ul>           |
||
| RelationTypeEvent     | event     | Name of the relation type                                                                                               |
|                       | label     | <ul><li>/org/inexor/events/types/relations/created</li><li>/org/inexor/events/types/relations/deleted</li></ul>         |
||
| EntityInstanceEvent   | event     | UUID of the entity instance                                                                                             |
|                       | label     | <ul><li>/org/inexor/events/instances/entities/created</li><li>/org/inexor/events/instances/entities/deleted</li></ul>   |
||
| RelationInstanceEvent | event     | UUID of the relation instance                                                                                           |
|                       | label     | <ul><li>/org/inexor/events/instances/relations/created</li><li>/org/inexor/events/instances/relations/deleted</li></ul> |
||
| FlowEvent             | event     | UUID of the flow                                                                                                        |
|                       | label     | <ul><li>/org/inexor/events/flows/created</li><li>/org/inexor/events/flows/deleted</li></ul>                             |
