### ISSUE TITLE
Components can have extensions

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#25]
### Goal

`Component`s should be able to provide extensions.

### Tasks

- [x] Add extensions to the model of `Component`s
- [x] Add builder for `Component`s
- [x] Add GraphQL resolvers
