### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#26]
### Goal

Secure the GraphQL endpoint with JWT

### Crate

[crate: jwt](https://crates.io/crates/jwt)

### Tasks

- [ ] Extend Configuration `config/graphql.toml`
    ```toml
    [authentication]
    enabled = true
    keystore_path = ""
    secret = ""
    issuer = ""
    audience = ""
    # Expiration in seconds
    expiration = 3600
    ```
- [ ] Create endpoint for login
    | Endpoint | Description        |
    |----------|--------------------|
    | `/auth/login` | Returns a newly created JWT |
    | `/auth/renew` | Renew JWT |
- [ ] Middleware: Check JWT token
