### ISSUE TITLE
 Plugin: GraphQL Client

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#31]
### Tasks

- [x] Setup Repository
- [x] Setup GitHub Actions
- [x] Implement Web Resource Provider
- [x] Integrate [Altair GraphQL Client](https://altair.sirmuel.design/)
- [x] Configuration plugins.toml
- [x] Documentation

| Name                                           | Repository                                                                   |
|------------------------------------------------|------------------------------------------------------------------------------|
| inexor-rgf-plugin-graphql-client | https://github.com/aschaeffer/inexor-rgf-plugin-graphql-client |
