### ISSUE TITLE
Plugin Test Suite: inexor-rgf-plugin-test-suite

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#34]
### Goal

Provide a user interface to test the functionality in a playground.

### Tasks

- [ ] Implement WebResourceProvider
- [ ] Load entity types + load test suite for each entity type
- [ ] Show tab for each test suite
- [ ] Create a first test suite for `AND`
- [ ] Render Test Suite

### Test Suite

- [ ] Entity Type Name
- [ ] Title
- [ ] Description
- [ ] GraphQL mutation for creating the test suite
- [ ] GraphQL mutation for updating the test suite
- [ ] GraphQL mutation for cleaning up the test suite
- [ ] Update interval
