### ISSUE TITLE
Plugin File: Reactive Component: fs_notify

### ISSUE THREAD

**Issue by aschaeffer** [aschaeffer/inexor-rgf-application#45]
### Goal

The component `fs_entity` triggers if the file with the given filename has been changed on the filesystem. This enables
hot reloading of file resources, for example JSON files, TOML configuration files and binary data.

### Component Flow

```mermaid
stateDiagram
  direction LR
  filename --> component_fs_notify
  state component_fs_notify {
    direction LR
    fn_watch
  }
  fn_watch --> trigger : externally changed
```

### Entity Flow

```mermaid
stateDiagram
  direction LR
  [*] --> trigger: manual trigger
  [*] --> filename
  state entity_load_something {
    filename --> component_fs_notify
    state component_fs_notify {
      direction LR
      fn_watch --> trigger : externally changed
      trigger --> result
    }
    state component_load_something {
      trigger --> fn_load
      filename --> fn_load
      fn_load --> result
    }
  }
  result --> [*]
```

### Use Cases

This component is indented to work together with several entity types, which loads data from disk.

* `load_json`+ `fs_notify`: (Re-) Load JSON files every time the file has been changed on the FS
* `load_config`+ `fs_notify`: (Re-) Load TOML configurations every time the file has been changed on the FS
* `load_binary_data`+ `fs_notify`: (Re-) Load binary data every time the file has been changed on the FS

### Components

`fs_notify` relies on the components `action` (property `trigger`) and `file` (property `filename`).

| *Component* |  *Property* |  *Data Type* |  *Socket Type* |
| --- | --- | --- | --- |
| action | trigger | bool | input |
| file | filename | string | input |
| fs_notify | | | |

### Tasks

- [x] Setup Plugin
- [x] Implement Component Behaviour
- [x] Make it work with + Test
  - [x] `load_json`
  - [x] `load_config`
  - [x] `load_binary_data`

### Resources

* https://github.com/notify-rs/notify
* https://github.com/aschaeffer/inexor-rgf-plugin-file
* https://github.com/aschaeffer/inexor-rgf-plugin-json
* https://github.com/aschaeffer/inexor-rgf-plugin-config
* https://github.com/aschaeffer/inexor-rgf-plugin-binary-data
